#!/bin/sh
# vim:syntax=sh

# 
#
# cli info usage 
#       usage function generator
#
# cli info help
#       help function generator
#
# cli info args
#       args function args generator
#
# cli doc 
#
# cli doc command COMMAND DESCRIPTION <<\END
#
#   summary text describing the function
#
# ARGS
#
#   [ARGNAME [DESCRIPTION]]
#   [ARGNAME [DESCRIPTION]]
#
#   the rest of these lines are reserved for
#   manpage style help output.
# 
# END
#
# EXAMPLE: (could be in .syntax script or in actual script file)
#
# cli syntax command github "interact with github service" <<\END
#
#   Provides the ability to interact with the GitHub REST API
#   service.
#   
# END
#

cli::doc::definition() {
  local COMMAND
  local CMD_DESCR
  local CMD_SUMMARY
  local ARGLIST
  local ARG

  read_heredoc METAFN <<__METAFN_END
    syntax_$FNNAME() {
      
    }
__METAFN_END
  eval '$MEAFN'
  
}
debug func $LINENO function 'cli::doc::definition() defined.'


