#!/usr/bin/printf %s: must be sourced from /bin/sh interpreter.\n
# vim:syntax=sh

# package require cli::debug
. "${CLILIB:?}/lib/cli/debug"

## require    NAMESPACE
##       sources file scope making it available in the interpreter
##


package::require() {
  local REQUIREMENTS
  local MODULE
  set -e
  while [ $# -gt 0 ]; do
    MODULE="$1"
    if [ -f "${CLILIB}/lib/`echo $MODULE | sed -r 's/::/\//g'`" ]; then
      REQUIREMENTS="$REQUIREMENTS $1"
    else
      error "require: could not find lib %s" "$1"
    fi
    shift
  done
  set +e
}
debug func $LINENO function 'cli::command::context() created.'




package() {
  SUBCOMMAND="${1:?}" ; shift
  case $SUBCOMMAND in
    require) package::require     "$@" ;;
    *)       error 'unknown subcommand "%s" must be: require.' "$SUBCOMMAND" ;;
  esac
}
debug func $LINENO function 'cli::command::context() created.'




